// File generated from our OpenAPI spec by Scalar. See README.md for details.

import type { Command } from 'commander';
import SDK from '../sdk/index';
import { createProgram, type CliClientOptionDefinition, type CliCommandDefinition } from '../cli/runtime';
import { completions } from '../cli/completions';

const clientOptions = [
  {
    clientKey: 'apiKey',
    sdkKey: 'apiKey',
    name: 'api-key',
    optionKey: 'apiKey',
    env: 'WARP_API_KEY',
    auth: true,
  },
] as const satisfies readonly CliClientOptionDefinition[];

const commands = [
  {
    resourcePath: ['benefits', 'healthPlans'],
    commandPath: ['benefits:health-plans', 'list'],
    methodName: 'list',
    summary: 'List Health Plans',
    description:
      'List company health plans. Defaults to active plans. A plan whose effectiveEndDate has elapsed is reported and filtered as terminated.',
    transport: 'http',
    iterable: false,
    callShape: 'params',
    positional: [],
    flags: [
      {
        name: 'limit',
        optionKey: 'limit',
        paramKey: 'limit',
        location: 'query',
        required: true,
        valueKind: 'string',
      },
      {
        name: 'after-id',
        optionKey: 'afterId',
        paramKey: 'afterId',
        location: 'query',
        required: false,
        valueKind: 'object',
      },
      {
        name: 'before-id',
        optionKey: 'beforeId',
        paramKey: 'beforeId',
        location: 'query',
        required: false,
        valueKind: 'object',
      },
      {
        name: 'types',
        optionKey: 'types',
        paramKey: 'types',
        location: 'query',
        required: false,
        valueKind: 'array',
      },
      {
        name: 'statuses',
        optionKey: 'statuses',
        paramKey: 'statuses',
        location: 'query',
        required: true,
        valueKind: 'array',
      },
      {
        name: 'carrier-ids',
        optionKey: 'carrierIds',
        paramKey: 'carrierIds',
        location: 'query',
        required: false,
        valueKind: 'array',
      },
    ],
  },
  {
    resourcePath: ['benefits', 'healthPlans'],
    commandPath: ['benefits:health-plans', 'get'],
    methodName: 'get',
    summary: 'Get Health Plan',
    description: 'Get a publicly visible company health plan by id.',
    transport: 'http',
    iterable: false,
    callShape: 'options',
    positional: [
      {
        name: 'id',
        optionKey: 'id',
        paramKey: 'id',
        location: 'path',
        required: true,
        valueKind: 'object',
      },
    ],
    flags: [],
  },
  {
    resourcePath: ['benefits', 'retirementPlans'],
    commandPath: ['benefits:retirement-plans', 'list'],
    methodName: 'list',
    summary: 'List Retirement Plans',
    description:
      'List company retirement plans. Defaults to active plans. A plan whose effectiveEndDate has elapsed is reported and filtered as terminated.',
    transport: 'http',
    iterable: false,
    callShape: 'params',
    positional: [],
    flags: [
      {
        name: 'limit',
        optionKey: 'limit',
        paramKey: 'limit',
        location: 'query',
        required: true,
        valueKind: 'string',
      },
      {
        name: 'after-id',
        optionKey: 'afterId',
        paramKey: 'afterId',
        location: 'query',
        required: false,
        valueKind: 'object',
      },
      {
        name: 'before-id',
        optionKey: 'beforeId',
        paramKey: 'beforeId',
        location: 'query',
        required: false,
        valueKind: 'object',
      },
      {
        name: 'types',
        optionKey: 'types',
        paramKey: 'types',
        location: 'query',
        required: false,
        valueKind: 'array',
      },
      {
        name: 'statuses',
        optionKey: 'statuses',
        paramKey: 'statuses',
        location: 'query',
        required: true,
        valueKind: 'array',
      },
    ],
  },
  {
    resourcePath: ['benefits', 'retirementPlans'],
    commandPath: ['benefits:retirement-plans', 'get'],
    methodName: 'get',
    summary: 'Get Retirement Plan',
    description: 'Get a company retirement plan by id, regardless of status.',
    transport: 'http',
    iterable: false,
    callShape: 'options',
    positional: [
      {
        name: 'id',
        optionKey: 'id',
        paramKey: 'id',
        location: 'path',
        required: true,
        valueKind: 'object',
      },
    ],
    flags: [],
  },
  {
    resourcePath: ['benefits', 'deductions'],
    commandPath: ['benefits:deductions', 'list'],
    methodName: 'list',
    summary: 'List Benefit Deductions',
    description:
      'List current payroll benefit deductions. Defaults to active deductions. A deduction whose effectiveEndDate has elapsed is reported and filtered as terminated.',
    transport: 'http',
    iterable: false,
    callShape: 'params',
    positional: [],
    flags: [
      {
        name: 'limit',
        optionKey: 'limit',
        paramKey: 'limit',
        location: 'query',
        required: true,
        valueKind: 'string',
      },
      {
        name: 'after-id',
        optionKey: 'afterId',
        paramKey: 'afterId',
        location: 'query',
        required: false,
        valueKind: 'object',
      },
      {
        name: 'before-id',
        optionKey: 'beforeId',
        paramKey: 'beforeId',
        location: 'query',
        required: false,
        valueKind: 'object',
      },
      {
        name: 'worker-ids',
        optionKey: 'workerIds',
        paramKey: 'workerIds',
        location: 'query',
        required: false,
        valueKind: 'array',
      },
      {
        name: 'categories',
        optionKey: 'categories',
        paramKey: 'categories',
        location: 'query',
        required: false,
        valueKind: 'array',
      },
      {
        name: 'types',
        optionKey: 'types',
        paramKey: 'types',
        location: 'query',
        required: false,
        valueKind: 'array',
      },
      {
        name: 'statuses',
        optionKey: 'statuses',
        paramKey: 'statuses',
        location: 'query',
        required: true,
        valueKind: 'array',
      },
      {
        name: 'health-plan-ids',
        optionKey: 'healthPlanIds',
        paramKey: 'healthPlanIds',
        location: 'query',
        required: false,
        valueKind: 'array',
      },
      {
        name: 'retirement-plan-ids',
        optionKey: 'retirementPlanIds',
        paramKey: 'retirementPlanIds',
        location: 'query',
        required: false,
        valueKind: 'array',
      },
    ],
  },
  {
    resourcePath: ['benefits', 'deductions'],
    commandPath: ['benefits:deductions', 'get'],
    methodName: 'get',
    summary: 'Get Benefit Deduction',
    description: 'Get the current version of a company benefit deduction by id.',
    transport: 'http',
    iterable: false,
    callShape: 'options',
    positional: [
      {
        name: 'id',
        optionKey: 'id',
        paramKey: 'id',
        location: 'path',
        required: true,
        valueKind: 'object',
      },
    ],
    flags: [],
  },
  {
    resourcePath: ['customFields'],
    commandPath: ['custom-fields', 'list'],
    methodName: 'list',
    summary: 'List Fields',
    description:
      'List the custom worker field definitions your API key can read. Each field belongs to a worker-data category; fields whose category your key cannot read are omitted unless the key holds workers:custom_fields.',
    transport: 'http',
    iterable: false,
    callShape: 'options',
    positional: [],
    flags: [],
  },
  {
    resourcePath: ['customFields'],
    commandPath: ['custom-fields', 'create'],
    methodName: 'create',
    summary: 'Create Field',
    description:
      'Create a custom worker field definition. The field type is immutable after creation. Select and multi_select fields can include their initial options. Access to values derives from the field category; requires the workers:custom_fields permission.',
    transport: 'http',
    iterable: false,
    callShape: 'body',
    positional: [],
    flags: [
      {
        name: 'name',
        optionKey: 'name',
        paramKey: 'name',
        location: 'body',
        required: true,
        valueKind: 'object',
      },
      {
        name: 'description',
        optionKey: 'description',
        paramKey: 'description',
        location: 'body',
        required: false,
        valueKind: 'string',
      },
      {
        name: 'type',
        optionKey: 'type',
        paramKey: 'type',
        location: 'body',
        required: true,
        valueKind: 'string',
      },
      {
        name: 'config',
        optionKey: 'config',
        paramKey: 'config',
        location: 'body',
        required: false,
        valueKind: 'object',
      },
      {
        name: 'category',
        optionKey: 'category',
        paramKey: 'category',
        location: 'body',
        required: true,
        valueKind: 'string',
      },
      {
        name: 'access-level',
        optionKey: 'accessLevel',
        paramKey: 'accessLevel',
        location: 'body',
        required: false,
        valueKind: 'string',
      },
      {
        name: 'input-by',
        optionKey: 'inputBy',
        paramKey: 'inputBy',
        location: 'body',
        required: false,
        valueKind: 'string',
      },
      {
        name: 'required',
        optionKey: 'required',
        paramKey: 'required',
        location: 'body',
        required: false,
        valueKind: 'boolean',
      },
      {
        name: 'options',
        optionKey: 'options',
        paramKey: 'options',
        location: 'body',
        required: false,
        valueKind: 'array',
      },
    ],
  },
  {
    resourcePath: ['customFields'],
    commandPath: ['custom-fields', 'retrieve'],
    methodName: 'retrieve',
    summary: 'Get Field',
    description:
      'Get a custom worker field definition, including its select options. Archived options may appear on existing worker values but cannot be newly selected.',
    transport: 'http',
    iterable: false,
    callShape: 'options',
    positional: [
      {
        name: 'id',
        optionKey: 'id',
        paramKey: 'id',
        location: 'path',
        required: true,
        valueKind: 'object',
      },
    ],
    flags: [],
  },
  {
    resourcePath: ['customFields'],
    commandPath: ['custom-fields', 'update'],
    methodName: 'update',
    summary: 'Update Field',
    description:
      'Update a custom worker field definition. The field type cannot be changed; create a new field instead. Requires the workers:custom_fields permission; changing the category, access level, or input source requires the manage level.',
    transport: 'http',
    iterable: false,
    callShape: 'body',
    positional: [
      {
        name: 'id',
        optionKey: 'id',
        paramKey: 'id',
        location: 'path',
        required: true,
        valueKind: 'object',
      },
    ],
    flags: [
      {
        name: 'name',
        optionKey: 'name',
        paramKey: 'name',
        location: 'body',
        required: false,
        valueKind: 'object',
      },
      {
        name: 'description',
        optionKey: 'description',
        paramKey: 'description',
        location: 'body',
        required: false,
        valueKind: 'string',
      },
      {
        name: 'config',
        optionKey: 'config',
        paramKey: 'config',
        location: 'body',
        required: false,
        valueKind: 'object',
      },
      {
        name: 'category',
        optionKey: 'category',
        paramKey: 'category',
        location: 'body',
        required: false,
        valueKind: 'string',
      },
      {
        name: 'access-level',
        optionKey: 'accessLevel',
        paramKey: 'accessLevel',
        location: 'body',
        required: false,
        valueKind: 'string',
      },
      {
        name: 'input-by',
        optionKey: 'inputBy',
        paramKey: 'inputBy',
        location: 'body',
        required: false,
        valueKind: 'string',
      },
      {
        name: 'required',
        optionKey: 'required',
        paramKey: 'required',
        location: 'body',
        required: false,
        valueKind: 'boolean',
      },
    ],
  },
  {
    resourcePath: ['customFields'],
    commandPath: ['custom-fields', 'archive'],
    methodName: 'archive',
    summary: 'Archive Field',
    description:
      'Archive a custom worker field. Archived fields keep their existing worker values but cannot receive new ones. Requires the workers:custom_fields permission at the manage level.',
    transport: 'http',
    iterable: false,
    callShape: 'options',
    positional: [
      {
        name: 'id',
        optionKey: 'id',
        paramKey: 'id',
        location: 'path',
        required: true,
        valueKind: 'object',
      },
    ],
    flags: [],
  },
  {
    resourcePath: ['customFields'],
    commandPath: ['custom-fields', 'create-option'],
    methodName: 'createOption',
    summary: 'Create Field Option',
    description:
      'Add an option to a select or multi_select custom worker field. The option value should be treated as stable; the label can change. Requires the workers:custom_fields permission.',
    transport: 'http',
    iterable: false,
    callShape: 'body',
    positional: [
      {
        name: 'id',
        optionKey: 'id',
        paramKey: 'id',
        location: 'path',
        required: true,
        valueKind: 'object',
      },
    ],
    flags: [
      {
        name: 'label',
        optionKey: 'label',
        paramKey: 'label',
        location: 'body',
        required: true,
        valueKind: 'object',
      },
      {
        name: 'value',
        optionKey: 'value',
        paramKey: 'value',
        location: 'body',
        required: true,
        valueKind: 'object',
      },
      {
        name: 'sort-order',
        optionKey: 'sortOrder',
        paramKey: 'sortOrder',
        location: 'body',
        required: false,
        valueKind: 'unknown',
      },
    ],
  },
  {
    resourcePath: ['customFields'],
    commandPath: ['custom-fields', 'update-option'],
    methodName: 'updateOption',
    summary: 'Update Field Option',
    description:
      'Update the label or sort order of a custom worker field option. Options of archived fields cannot be edited. Requires the workers:custom_fields permission.',
    transport: 'http',
    iterable: false,
    callShape: 'body',
    positional: [
      {
        name: 'id',
        optionKey: 'id',
        paramKey: 'id',
        location: 'path',
        required: true,
        valueKind: 'object',
      },
    ],
    flags: [
      {
        name: 'label',
        optionKey: 'label',
        paramKey: 'label',
        location: 'body',
        required: false,
        valueKind: 'object',
      },
      {
        name: 'sort-order',
        optionKey: 'sortOrder',
        paramKey: 'sortOrder',
        location: 'body',
        required: false,
        valueKind: 'unknown',
      },
    ],
  },
  {
    resourcePath: ['customFields'],
    commandPath: ['custom-fields', 'delete-option'],
    methodName: 'deleteOption',
    summary: 'Delete Unused Field Option',
    description:
      'Delete a custom worker field option that is not applied to any worker. Options in use must be archived instead. Requires the workers:custom_fields permission at the manage level.',
    transport: 'http',
    iterable: false,
    callShape: 'options',
    positional: [
      {
        name: 'id',
        optionKey: 'id',
        paramKey: 'id',
        location: 'path',
        required: true,
        valueKind: 'object',
      },
    ],
    flags: [],
  },
  {
    resourcePath: ['customFields'],
    commandPath: ['custom-fields', 'archive-option'],
    methodName: 'archiveOption',
    summary: 'Archive Field Option',
    description:
      'Archive a custom worker field option. Archived options remain on existing worker values but cannot be newly selected. Requires the workers:custom_fields permission at the manage level.',
    transport: 'http',
    iterable: false,
    callShape: 'options',
    positional: [
      {
        name: 'id',
        optionKey: 'id',
        paramKey: 'id',
        location: 'path',
        required: true,
        valueKind: 'object',
      },
    ],
    flags: [],
  },
  {
    resourcePath: ['customFields'],
    commandPath: ['custom-fields', 'list-values'],
    methodName: 'listValues',
    summary: 'List Field Values',
    description:
      'List custom field values for workers, optionally filtered by worker or field. Values are returned only for fields whose category your API key can read.',
    transport: 'http',
    iterable: false,
    callShape: 'params',
    positional: [],
    flags: [
      {
        name: 'worker-ids',
        optionKey: 'workerIds',
        paramKey: 'workerIds',
        location: 'query',
        required: false,
        valueKind: 'array',
      },
      {
        name: 'field-ids',
        optionKey: 'fieldIds',
        paramKey: 'fieldIds',
        location: 'query',
        required: false,
        valueKind: 'array',
      },
    ],
  },
  {
    resourcePath: ['customFields'],
    commandPath: ['custom-fields', 'upsert-value'],
    methodName: 'upsertValue',
    summary: 'Set Field Value',
    description:
      "Create or replace a worker's value for a custom field. The value shape must match the field type, and your API key must hold write on the field's category.",
    transport: 'http',
    iterable: false,
    callShape: 'body',
    positional: [],
    flags: [
      {
        name: 'worker-id',
        optionKey: 'workerId',
        paramKey: 'workerId',
        location: 'body',
        required: true,
        valueKind: 'object',
      },
      {
        name: 'field-id',
        optionKey: 'fieldId',
        paramKey: 'fieldId',
        location: 'body',
        required: true,
        valueKind: 'object',
      },
      {
        name: 'value',
        optionKey: 'value',
        paramKey: 'value',
        location: 'body',
        required: true,
        valueKind: 'unknown',
      },
    ],
  },
  {
    resourcePath: ['customFields'],
    commandPath: ['custom-fields', 'clear-value'],
    methodName: 'clearValue',
    summary: 'Clear Field Value',
    description:
      "Remove a worker's value for a custom field. Your API key must hold write on the field's category.",
    transport: 'http',
    iterable: false,
    callShape: 'params',
    positional: [],
    flags: [
      {
        name: 'worker-id',
        optionKey: 'workerId',
        paramKey: 'workerId',
        location: 'query',
        required: true,
        valueKind: 'object',
      },
      {
        name: 'field-id',
        optionKey: 'fieldId',
        paramKey: 'fieldId',
        location: 'query',
        required: true,
        valueKind: 'object',
      },
    ],
  },
  {
    resourcePath: ['departments'],
    commandPath: ['departments', 'list'],
    methodName: 'list',
    summary: 'List Departments',
    description: 'List all departments for your company.',
    transport: 'http',
    iterable: false,
    callShape: 'params',
    positional: [],
    flags: [
      {
        name: 'limit',
        optionKey: 'limit',
        paramKey: 'limit',
        location: 'query',
        required: true,
        valueKind: 'string',
      },
      {
        name: 'after-id',
        optionKey: 'afterId',
        paramKey: 'afterId',
        location: 'query',
        required: false,
        valueKind: 'object',
      },
      {
        name: 'before-id',
        optionKey: 'beforeId',
        paramKey: 'beforeId',
        location: 'query',
        required: false,
        valueKind: 'object',
      },
    ],
  },
  {
    resourcePath: ['departments'],
    commandPath: ['departments', 'create'],
    methodName: 'create',
    summary: 'Create Department',
    description: 'Create a new department.',
    transport: 'http',
    iterable: false,
    callShape: 'body',
    positional: [],
    flags: [
      {
        name: 'name',
        optionKey: 'name',
        paramKey: 'name',
        location: 'body',
        required: true,
        valueKind: 'object',
      },
    ],
  },
  {
    resourcePath: ['departments'],
    commandPath: ['departments', 'update'],
    methodName: 'update',
    summary: 'Update Department',
    description: 'Update an existing department.',
    transport: 'http',
    iterable: false,
    callShape: 'body',
    positional: [
      {
        name: 'id',
        optionKey: 'id',
        paramKey: 'id',
        location: 'path',
        required: true,
        valueKind: 'object',
      },
    ],
    flags: [
      {
        name: 'name',
        optionKey: 'name',
        paramKey: 'name',
        location: 'body',
        required: false,
        valueKind: 'string',
      },
    ],
  },
  {
    resourcePath: ['offers'],
    commandPath: ['offers', 'list'],
    methodName: 'list',
    summary: 'List Offers',
    description: 'List the candidate offers for your company.',
    transport: 'http',
    iterable: false,
    callShape: 'params',
    positional: [],
    flags: [
      {
        name: 'limit',
        optionKey: 'limit',
        paramKey: 'limit',
        location: 'query',
        required: true,
        valueKind: 'string',
      },
      {
        name: 'after-id',
        optionKey: 'afterId',
        paramKey: 'afterId',
        location: 'query',
        required: false,
        valueKind: 'object',
      },
      {
        name: 'before-id',
        optionKey: 'beforeId',
        paramKey: 'beforeId',
        location: 'query',
        required: false,
        valueKind: 'object',
      },
      {
        name: 'statuses',
        optionKey: 'statuses',
        paramKey: 'statuses',
        location: 'query',
        required: false,
        valueKind: 'array',
      },
      {
        name: 'worker-types',
        optionKey: 'workerTypes',
        paramKey: 'workerTypes',
        location: 'query',
        required: false,
        valueKind: 'array',
      },
      {
        name: 'candidate-email',
        optionKey: 'candidateEmail',
        paramKey: 'candidateEmail',
        location: 'query',
        required: false,
        valueKind: 'object',
      },
    ],
  },
  {
    resourcePath: ['offers'],
    commandPath: ['offers', 'create'],
    methodName: 'create',
    summary: 'Create Offer',
    description:
      'Create and send a candidate offer. The candidate receives an email with a link to the offer portal.',
    transport: 'http',
    iterable: false,
    callShape: 'body',
    positional: [],
    flags: [
      {
        name: 'candidate',
        optionKey: 'candidate',
        paramKey: 'candidate',
        location: 'body',
        required: true,
        valueKind: 'object',
      },
      {
        name: 'candidate.first-name',
        optionKey: 'candidate.firstName',
        paramKey: 'candidate',
        location: 'body',
        required: false,
        valueKind: 'object',
        objectPath: ['firstName'],
      },
      {
        name: 'candidate.last-name',
        optionKey: 'candidate.lastName',
        paramKey: 'candidate',
        location: 'body',
        required: false,
        valueKind: 'object',
        objectPath: ['lastName'],
      },
      {
        name: 'candidate.email',
        optionKey: 'candidate.email',
        paramKey: 'candidate',
        location: 'body',
        required: false,
        valueKind: 'object',
        objectPath: ['email'],
      },
      {
        name: 'candidate.contractor-details',
        optionKey: 'candidate.contractorDetails',
        paramKey: 'candidate',
        location: 'body',
        required: false,
        valueKind: 'object',
        objectPath: ['contractorDetails'],
      },
      {
        name: 'candidate.contractor-details.is-business',
        optionKey: 'candidate.contractorDetails.isBusiness',
        paramKey: 'candidate',
        location: 'body',
        required: false,
        valueKind: 'boolean',
        objectPath: ['contractorDetails', 'isBusiness'],
      },
      {
        name: 'candidate.contractor-details.legal-business-name',
        optionKey: 'candidate.contractorDetails.legalBusinessName',
        paramKey: 'candidate',
        location: 'body',
        required: false,
        valueKind: 'string',
        objectPath: ['contractorDetails', 'legalBusinessName'],
      },
      {
        name: 'position',
        optionKey: 'position',
        paramKey: 'position',
        location: 'body',
        required: true,
        valueKind: 'object',
      },
      {
        name: 'position.title',
        optionKey: 'position.title',
        paramKey: 'position',
        location: 'body',
        required: false,
        valueKind: 'object',
        objectPath: ['title'],
      },
      {
        name: 'position.start-date',
        optionKey: 'position.startDate',
        paramKey: 'position',
        location: 'body',
        required: false,
        valueKind: 'object',
        objectPath: ['startDate'],
      },
      {
        name: 'position.country',
        optionKey: 'position.country',
        paramKey: 'position',
        location: 'body',
        required: false,
        valueKind: 'string',
        objectPath: ['country'],
      },
      {
        name: 'position.scope-of-work',
        optionKey: 'position.scopeOfWork',
        paramKey: 'position',
        location: 'body',
        required: false,
        valueKind: 'string',
        objectPath: ['scopeOfWork'],
      },
      {
        name: 'department-id',
        optionKey: 'departmentId',
        paramKey: 'departmentId',
        location: 'body',
        required: false,
        valueKind: 'object',
      },
      {
        name: 'workplace-id',
        optionKey: 'workplaceId',
        paramKey: 'workplaceId',
        location: 'body',
        required: false,
        valueKind: 'object',
      },
      {
        name: 'manager-id',
        optionKey: 'managerId',
        paramKey: 'managerId',
        location: 'body',
        required: false,
        valueKind: 'object',
      },
      {
        name: 'worker-type',
        optionKey: 'workerType',
        paramKey: 'workerType',
        location: 'body',
        required: true,
        valueKind: 'string',
      },
      {
        name: 'compensation',
        optionKey: 'compensation',
        paramKey: 'compensation',
        location: 'body',
        required: true,
        valueKind: 'object',
      },
      {
        name: 'compensation.pay-basis',
        optionKey: 'compensation.payBasis',
        paramKey: 'compensation',
        location: 'body',
        required: false,
        valueKind: 'string',
        objectPath: ['payBasis'],
      },
      {
        name: 'compensation.pay-currency',
        optionKey: 'compensation.payCurrency',
        paramKey: 'compensation',
        location: 'body',
        required: false,
        valueKind: 'string',
        objectPath: ['payCurrency'],
      },
      {
        name: 'compensation.pay-rate',
        optionKey: 'compensation.payRate',
        paramKey: 'compensation',
        location: 'body',
        required: false,
        valueKind: 'object',
        objectPath: ['payRate'],
      },
      {
        name: 'compensation.pay-type',
        optionKey: 'compensation.payType',
        paramKey: 'compensation',
        location: 'body',
        required: false,
        valueKind: 'string',
        objectPath: ['payType'],
      },
      {
        name: 'compensation.pay-variable-rate',
        optionKey: 'compensation.payVariableRate',
        paramKey: 'compensation',
        location: 'body',
        required: false,
        valueKind: 'object',
        objectPath: ['payVariableRate'],
      },
      {
        name: 'compensation.sign-on-bonus',
        optionKey: 'compensation.signOnBonus',
        paramKey: 'compensation',
        location: 'body',
        required: false,
        valueKind: 'object',
        objectPath: ['signOnBonus'],
      },
      {
        name: 'compensation.relocation-bonus',
        optionKey: 'compensation.relocationBonus',
        paramKey: 'compensation',
        location: 'body',
        required: false,
        valueKind: 'object',
        objectPath: ['relocationBonus'],
      },
      {
        name: 'compensation.stock-options',
        optionKey: 'compensation.stockOptions',
        paramKey: 'compensation',
        location: 'body',
        required: false,
        valueKind: 'object',
        objectPath: ['stockOptions'],
      },
      {
        name: 'compensation.vesting-schedule-months',
        optionKey: 'compensation.vestingScheduleMonths',
        paramKey: 'compensation',
        location: 'body',
        required: false,
        valueKind: 'object',
        objectPath: ['vestingScheduleMonths'],
      },
      {
        name: 'compensation.cliff-months',
        optionKey: 'compensation.cliffMonths',
        paramKey: 'compensation',
        location: 'body',
        required: false,
        valueKind: 'object',
        objectPath: ['cliffMonths'],
      },
      {
        name: 'expiration-time',
        optionKey: 'expirationTime',
        paramKey: 'expirationTime',
        location: 'body',
        required: false,
        valueKind: 'string',
      },
    ],
  },
  {
    resourcePath: ['offers'],
    commandPath: ['offers', 'void'],
    methodName: 'void',
    summary: 'Void Offer',
    description: 'Void a previously sent offer. Only sent offers can be voided.',
    transport: 'http',
    iterable: false,
    callShape: 'options',
    positional: [
      {
        name: 'id',
        optionKey: 'id',
        paramKey: 'id',
        location: 'path',
        required: true,
        valueKind: 'object',
      },
    ],
    flags: [],
  },
  {
    resourcePath: ['offers'],
    commandPath: ['offers', 'extend-deadline'],
    methodName: 'extendDeadline',
    summary: 'Extend Offer Deadline',
    description: 'Extend the expiration deadline of a sent offer.',
    transport: 'http',
    iterable: false,
    callShape: 'body',
    positional: [
      {
        name: 'id',
        optionKey: 'id',
        paramKey: 'id',
        location: 'path',
        required: true,
        valueKind: 'object',
      },
    ],
    flags: [
      {
        name: 'expiration-time',
        optionKey: 'expirationTime',
        paramKey: 'expirationTime',
        location: 'body',
        required: true,
        valueKind: 'string',
      },
    ],
  },
  {
    resourcePath: ['offers'],
    commandPath: ['offers', 'resend'],
    methodName: 'resend',
    summary: 'Resend Offer',
    description: 'Resend the offer email to the candidate for a sent offer.',
    transport: 'http',
    iterable: false,
    callShape: 'options',
    positional: [
      {
        name: 'id',
        optionKey: 'id',
        paramKey: 'id',
        location: 'path',
        required: true,
        valueKind: 'object',
      },
    ],
    flags: [],
  },
  {
    resourcePath: ['timeOff'],
    commandPath: ['time-off', 'list-assignments'],
    methodName: 'listAssignments',
    summary: 'List Time Off Assignments',
    description:
      'Time off assignments are mappings between workers and time off policies. Useful for finding out which policies a worker is assigned to, or which workers are assigned to a given policy.',
    transport: 'http',
    iterable: false,
    callShape: 'params',
    positional: [],
    flags: [
      {
        name: 'limit',
        optionKey: 'limit',
        paramKey: 'limit',
        location: 'query',
        required: true,
        valueKind: 'string',
      },
      {
        name: 'after-id',
        optionKey: 'afterId',
        paramKey: 'afterId',
        location: 'query',
        required: false,
        valueKind: 'string',
      },
      {
        name: 'before-id',
        optionKey: 'beforeId',
        paramKey: 'beforeId',
        location: 'query',
        required: false,
        valueKind: 'string',
      },
      {
        name: 'policy-ids',
        optionKey: 'policyIds',
        paramKey: 'policyIds',
        location: 'query',
        required: false,
        valueKind: 'array',
      },
      {
        name: 'worker-ids',
        optionKey: 'workerIds',
        paramKey: 'workerIds',
        location: 'query',
        required: false,
        valueKind: 'array',
      },
    ],
  },
  {
    resourcePath: ['timeOff'],
    commandPath: ['time-off', 'list-balances'],
    methodName: 'listBalances',
    summary: 'List Time Off Balances',
    description: 'Get worker remaining time-off balances.',
    transport: 'http',
    iterable: false,
    callShape: 'params',
    positional: [],
    flags: [
      {
        name: 'limit',
        optionKey: 'limit',
        paramKey: 'limit',
        location: 'query',
        required: true,
        valueKind: 'string',
      },
      {
        name: 'after-id',
        optionKey: 'afterId',
        paramKey: 'afterId',
        location: 'query',
        required: false,
        valueKind: 'string',
      },
      {
        name: 'before-id',
        optionKey: 'beforeId',
        paramKey: 'beforeId',
        location: 'query',
        required: false,
        valueKind: 'string',
      },
      {
        name: 'policy-ids',
        optionKey: 'policyIds',
        paramKey: 'policyIds',
        location: 'query',
        required: false,
        valueKind: 'array',
      },
      {
        name: 'worker-ids',
        optionKey: 'workerIds',
        paramKey: 'workerIds',
        location: 'query',
        required: false,
        valueKind: 'array',
      },
      {
        name: 'start-date',
        optionKey: 'startDate',
        paramKey: 'startDate',
        location: 'query',
        required: false,
        valueKind: 'string',
      },
      {
        name: 'end-date',
        optionKey: 'endDate',
        paramKey: 'endDate',
        location: 'query',
        required: false,
        valueKind: 'string',
      },
    ],
  },
  {
    resourcePath: ['timeOff'],
    commandPath: ['time-off', 'list-requests'],
    methodName: 'listRequests',
    summary: 'List Time Off Requests',
    description: 'Get the time off requests that workers in your company have made.',
    transport: 'http',
    iterable: false,
    callShape: 'params',
    positional: [],
    flags: [
      {
        name: 'limit',
        optionKey: 'limit',
        paramKey: 'limit',
        location: 'query',
        required: true,
        valueKind: 'string',
      },
      {
        name: 'after-id',
        optionKey: 'afterId',
        paramKey: 'afterId',
        location: 'query',
        required: false,
        valueKind: 'string',
      },
      {
        name: 'before-id',
        optionKey: 'beforeId',
        paramKey: 'beforeId',
        location: 'query',
        required: false,
        valueKind: 'string',
      },
      {
        name: 'statuses',
        optionKey: 'statuses',
        paramKey: 'statuses',
        location: 'query',
        required: false,
        valueKind: 'array',
      },
      {
        name: 'policy-ids',
        optionKey: 'policyIds',
        paramKey: 'policyIds',
        location: 'query',
        required: false,
        valueKind: 'array',
      },
      {
        name: 'worker-ids',
        optionKey: 'workerIds',
        paramKey: 'workerIds',
        location: 'query',
        required: false,
        valueKind: 'array',
      },
      {
        name: 'starts-on-or-after',
        optionKey: 'startsOnOrAfter',
        paramKey: 'startsOnOrAfter',
        location: 'query',
        required: false,
        valueKind: 'string',
      },
      {
        name: 'starts-before',
        optionKey: 'startsBefore',
        paramKey: 'startsBefore',
        location: 'query',
        required: false,
        valueKind: 'string',
      },
      {
        name: 'ends-on-or-after',
        optionKey: 'endsOnOrAfter',
        paramKey: 'endsOnOrAfter',
        location: 'query',
        required: false,
        valueKind: 'string',
      },
      {
        name: 'ends-before',
        optionKey: 'endsBefore',
        paramKey: 'endsBefore',
        location: 'query',
        required: false,
        valueKind: 'string',
      },
    ],
  },
  {
    resourcePath: ['timeOff', 'policies'],
    commandPath: ['time-off:policies', 'time-off-get'],
    methodName: 'timeOffGet',
    summary: 'List Time Off Policies',
    description: 'Get the time off policies for your company',
    transport: 'http',
    iterable: false,
    callShape: 'params',
    positional: [],
    flags: [
      {
        name: 'limit',
        optionKey: 'limit',
        paramKey: 'limit',
        location: 'query',
        required: true,
        valueKind: 'string',
      },
      {
        name: 'after-id',
        optionKey: 'afterId',
        paramKey: 'afterId',
        location: 'query',
        required: false,
        valueKind: 'object',
      },
      {
        name: 'before-id',
        optionKey: 'beforeId',
        paramKey: 'beforeId',
        location: 'query',
        required: false,
        valueKind: 'object',
      },
    ],
  },
  {
    resourcePath: ['timeOff', 'policies'],
    commandPath: ['time-off:policies', 'time-off-get2'],
    methodName: 'timeOffGet2',
    summary: 'Get Time Off Policy',
    description: 'Get a specific time off policy by id',
    transport: 'http',
    iterable: false,
    callShape: 'options',
    positional: [
      {
        name: 'id',
        optionKey: 'id',
        paramKey: 'id',
        location: 'path',
        required: true,
        valueKind: 'object',
      },
    ],
    flags: [],
  },
  {
    resourcePath: ['workers'],
    commandPath: ['workers', 'list'],
    methodName: 'list',
    summary: 'List Workers',
    description:
      'List all workers. Workers include anyone employed by the company, whether US or international, full-time employees or contractors.',
    transport: 'http',
    iterable: false,
    callShape: 'params',
    positional: [],
    flags: [
      {
        name: 'limit',
        optionKey: 'limit',
        paramKey: 'limit',
        location: 'query',
        required: true,
        valueKind: 'string',
      },
      {
        name: 'after-id',
        optionKey: 'afterId',
        paramKey: 'afterId',
        location: 'query',
        required: false,
        valueKind: 'object',
      },
      {
        name: 'before-id',
        optionKey: 'beforeId',
        paramKey: 'beforeId',
        location: 'query',
        required: false,
        valueKind: 'object',
      },
      {
        name: 'statuses',
        optionKey: 'statuses',
        paramKey: 'statuses',
        location: 'query',
        required: false,
        valueKind: 'array',
      },
      {
        name: 'types',
        optionKey: 'types',
        paramKey: 'types',
        location: 'query',
        required: false,
        valueKind: 'array',
      },
      {
        name: 'work-email',
        optionKey: 'workEmail',
        paramKey: 'workEmail',
        location: 'query',
        required: false,
        valueKind: 'string',
      },
    ],
  },
  {
    resourcePath: ['workers'],
    commandPath: ['workers', 'retrieve'],
    methodName: 'retrieve',
    summary: 'Get Worker',
    description: 'Get a specific worker by id.',
    transport: 'http',
    iterable: false,
    callShape: 'options',
    positional: [
      {
        name: 'id',
        optionKey: 'id',
        paramKey: 'id',
        location: 'path',
        required: true,
        valueKind: 'object',
      },
    ],
    flags: [],
  },
  {
    resourcePath: ['workers'],
    commandPath: ['workers', 'delete'],
    methodName: 'delete',
    summary: 'Delete Worker',
    description:
      'Delete a worker. Only workers who have not yet completed onboarding can be deleted. Active workers must be properly offboarded.',
    transport: 'http',
    iterable: false,
    callShape: 'options',
    positional: [
      {
        name: 'id',
        optionKey: 'id',
        paramKey: 'id',
        location: 'path',
        required: true,
        valueKind: 'object',
      },
    ],
    flags: [],
  },
  {
    resourcePath: ['workers'],
    commandPath: ['workers', 'create-employee'],
    methodName: 'createEmployee',
    summary: 'Create Employee',
    description:
      'Create a new US employee. The worker will be created in draft status and must be invited separately via the invite endpoint. If hiring in a state without an existing tax registration, you must specify the stateRegistration field.',
    transport: 'http',
    iterable: false,
    callShape: 'body',
    positional: [],
    flags: [
      {
        name: 'first-name',
        optionKey: 'firstName',
        paramKey: 'firstName',
        location: 'body',
        required: true,
        valueKind: 'object',
      },
      {
        name: 'last-name',
        optionKey: 'lastName',
        paramKey: 'lastName',
        location: 'body',
        required: true,
        valueKind: 'object',
      },
      {
        name: 'position',
        optionKey: 'position',
        paramKey: 'position',
        location: 'body',
        required: true,
        valueKind: 'object',
      },
      {
        name: 'start-date',
        optionKey: 'startDate',
        paramKey: 'startDate',
        location: 'body',
        required: true,
        valueKind: 'object',
      },
      {
        name: 'email',
        optionKey: 'email',
        paramKey: 'email',
        location: 'body',
        required: true,
        valueKind: 'object',
      },
      {
        name: 'work-email',
        optionKey: 'workEmail',
        paramKey: 'workEmail',
        location: 'body',
        required: false,
        valueKind: 'object',
      },
      {
        name: 'require-i9',
        optionKey: 'requireI9',
        paramKey: 'requireI9',
        location: 'body',
        required: false,
        valueKind: 'boolean',
      },
      {
        name: 'state-registration',
        optionKey: 'stateRegistration',
        paramKey: 'stateRegistration',
        location: 'body',
        required: false,
        valueKind: 'string',
      },
      {
        name: 'department-id',
        optionKey: 'departmentId',
        paramKey: 'departmentId',
        location: 'body',
        required: true,
        valueKind: 'object',
      },
      {
        name: 'manager-id',
        optionKey: 'managerId',
        paramKey: 'managerId',
        location: 'body',
        required: true,
        valueKind: 'object',
      },
      {
        name: 'stock-options',
        optionKey: 'stockOptions',
        paramKey: 'stockOptions',
        location: 'body',
        required: false,
        valueKind: 'unknown',
      },
      {
        name: 'work-location',
        optionKey: 'workLocation',
        paramKey: 'workLocation',
        location: 'body',
        required: true,
        description:
          'Where the employee will work. Either an existing company workplace or a remote US state.',
        valueKind: 'unknown',
      },
      {
        name: 'compensation',
        optionKey: 'compensation',
        paramKey: 'compensation',
        location: 'body',
        required: true,
        description: "The employee's base compensation.",
        valueKind: 'object',
      },
      {
        name: 'compensation.amount',
        optionKey: 'compensation.amount',
        paramKey: 'compensation',
        location: 'body',
        required: false,
        valueKind: 'object',
        objectPath: ['amount'],
      },
      {
        name: 'compensation.per',
        optionKey: 'compensation.per',
        paramKey: 'compensation',
        location: 'body',
        required: false,
        description: 'Whether the amount is per hour or per year.',
        valueKind: 'string',
        objectPath: ['per'],
      },
      {
        name: 'pay-schedule',
        optionKey: 'paySchedule',
        paramKey: 'paySchedule',
        location: 'body',
        required: false,
        valueKind: 'string',
      },
    ],
  },
  {
    resourcePath: ['workers'],
    commandPath: ['workers', 'create-contractor'],
    methodName: 'createContractor',
    summary: 'Create Contractor',
    description:
      'Create a new contractor. The worker will be created in draft status and must be invited separately via the invite endpoint. For business contractors, the businessName field is required.',
    transport: 'http',
    iterable: false,
    callShape: 'body',
    positional: [],
    flags: [
      {
        name: 'entity-type',
        optionKey: 'entityType',
        paramKey: 'entityType',
        location: 'body',
        required: true,
        description: 'Whether the contractor is an individual person or a business entity.',
        valueKind: 'string',
      },
      {
        name: 'first-name',
        optionKey: 'firstName',
        paramKey: 'firstName',
        location: 'body',
        required: true,
        valueKind: 'object',
      },
      {
        name: 'last-name',
        optionKey: 'lastName',
        paramKey: 'lastName',
        location: 'body',
        required: true,
        valueKind: 'object',
      },
      {
        name: 'position',
        optionKey: 'position',
        paramKey: 'position',
        location: 'body',
        required: true,
        valueKind: 'object',
      },
      {
        name: 'business-name',
        optionKey: 'businessName',
        paramKey: 'businessName',
        location: 'body',
        required: false,
        valueKind: 'object',
      },
      {
        name: 'scope-of-work',
        optionKey: 'scopeOfWork',
        paramKey: 'scopeOfWork',
        location: 'body',
        required: false,
        valueKind: 'string',
      },
      {
        name: 'start-date',
        optionKey: 'startDate',
        paramKey: 'startDate',
        location: 'body',
        required: true,
        valueKind: 'object',
      },
      {
        name: 'email',
        optionKey: 'email',
        paramKey: 'email',
        location: 'body',
        required: true,
        valueKind: 'object',
      },
      {
        name: 'work-email',
        optionKey: 'workEmail',
        paramKey: 'workEmail',
        location: 'body',
        required: false,
        valueKind: 'object',
      },
      {
        name: 'department-id',
        optionKey: 'departmentId',
        paramKey: 'departmentId',
        location: 'body',
        required: true,
        valueKind: 'object',
      },
      {
        name: 'manager-id',
        optionKey: 'managerId',
        paramKey: 'managerId',
        location: 'body',
        required: true,
        valueKind: 'object',
      },
      {
        name: 'work-country',
        optionKey: 'workCountry',
        paramKey: 'workCountry',
        location: 'body',
        required: true,
        valueKind: 'string',
      },
      {
        name: 'compensation',
        optionKey: 'compensation',
        paramKey: 'compensation',
        location: 'body',
        required: false,
        valueKind: 'object',
      },
      {
        name: 'compensation.currency',
        optionKey: 'compensation.currency',
        paramKey: 'compensation',
        location: 'body',
        required: false,
        valueKind: 'string',
        objectPath: ['currency'],
      },
      {
        name: 'compensation.amount',
        optionKey: 'compensation.amount',
        paramKey: 'compensation',
        location: 'body',
        required: false,
        valueKind: 'object',
        objectPath: ['amount'],
      },
      {
        name: 'compensation.per',
        optionKey: 'compensation.per',
        paramKey: 'compensation',
        location: 'body',
        required: false,
        description: 'The pay period for the compensation amount.',
        valueKind: 'string',
        objectPath: ['per'],
      },
      {
        name: 'pay-schedule',
        optionKey: 'paySchedule',
        paramKey: 'paySchedule',
        location: 'body',
        required: false,
        valueKind: 'string',
      },
    ],
  },
  {
    resourcePath: ['workers'],
    commandPath: ['workers', 'invite'],
    methodName: 'invite',
    summary: 'Invite Worker',
    description:
      'Send or resend the worker invite so they can accept and complete onboarding to Warp. If the worker has already been invited, the invite will be resent with extended validity.',
    transport: 'http',
    iterable: false,
    callShape: 'options',
    positional: [
      {
        name: 'id',
        optionKey: 'id',
        paramKey: 'id',
        location: 'path',
        required: true,
        valueKind: 'object',
      },
    ],
    flags: [],
  },
  {
    resourcePath: ['workplaces'],
    commandPath: ['workplaces', 'list'],
    methodName: 'list',
    summary: 'List Workplaces',
    description: 'List all workplaces for your company.',
    transport: 'http',
    iterable: false,
    callShape: 'params',
    positional: [],
    flags: [
      {
        name: 'limit',
        optionKey: 'limit',
        paramKey: 'limit',
        location: 'query',
        required: true,
        valueKind: 'string',
      },
      {
        name: 'after-id',
        optionKey: 'afterId',
        paramKey: 'afterId',
        location: 'query',
        required: false,
        valueKind: 'object',
      },
      {
        name: 'before-id',
        optionKey: 'beforeId',
        paramKey: 'beforeId',
        location: 'query',
        required: false,
        valueKind: 'object',
      },
    ],
  },
  {
    resourcePath: ['workplaces'],
    commandPath: ['workplaces', 'create'],
    methodName: 'create',
    summary: 'Create Workplace',
    description: 'Create a new workplace.',
    transport: 'http',
    iterable: false,
    callShape: 'body',
    positional: [],
    flags: [
      {
        name: 'name',
        optionKey: 'name',
        paramKey: 'name',
        location: 'body',
        required: true,
        valueKind: 'object',
      },
      {
        name: 'type',
        optionKey: 'type',
        paramKey: 'type',
        location: 'body',
        required: true,
        valueKind: 'string',
      },
      {
        name: 'address',
        optionKey: 'address',
        paramKey: 'address',
        location: 'body',
        required: true,
        description: 'A valid US address',
        valueKind: 'object',
      },
      {
        name: 'address.line1',
        optionKey: 'address.line1',
        paramKey: 'address',
        location: 'body',
        required: false,
        valueKind: 'object',
        objectPath: ['line1'],
      },
      {
        name: 'address.line2',
        optionKey: 'address.line2',
        paramKey: 'address',
        location: 'body',
        required: false,
        valueKind: 'string',
        objectPath: ['line2'],
      },
      {
        name: 'address.city',
        optionKey: 'address.city',
        paramKey: 'address',
        location: 'body',
        required: false,
        valueKind: 'string',
        objectPath: ['city'],
      },
      {
        name: 'address.postal-code',
        optionKey: 'address.postalCode',
        paramKey: 'address',
        location: 'body',
        required: false,
        valueKind: 'string',
        objectPath: ['postalCode'],
      },
      {
        name: 'address.state',
        optionKey: 'address.state',
        paramKey: 'address',
        location: 'body',
        required: false,
        valueKind: 'string',
        objectPath: ['state'],
      },
      {
        name: 'address.country',
        optionKey: 'address.country',
        paramKey: 'address',
        location: 'body',
        required: false,
        valueKind: 'string',
        objectPath: ['country'],
      },
    ],
  },
  {
    resourcePath: ['workplaces'],
    commandPath: ['workplaces', 'update'],
    methodName: 'update',
    summary: 'Update Workplace',
    description: 'Update an existing workplace.',
    transport: 'http',
    iterable: false,
    callShape: 'body',
    positional: [
      {
        name: 'id',
        optionKey: 'id',
        paramKey: 'id',
        location: 'path',
        required: true,
        valueKind: 'object',
      },
    ],
    flags: [
      {
        name: 'name',
        optionKey: 'name',
        paramKey: 'name',
        location: 'body',
        required: false,
        valueKind: 'string',
      },
    ],
  },
] as const satisfies readonly CliCommandDefinition[];

export const getProgram = (): Command =>
  createProgram({
    SDK,
    binaryName: 'warp',
    version: '0.1.0', // x-release-please-version
    description: 'CLI for Warp',
    defaultFormat: 'auto',
    defaultErrorFormat: 'auto',
    clientOptions,
    commands,
    completions,
  });
