#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")/.."

# Mark the necessary Go modules as private to avoid Go's proxy
export GOPRIVATE="${GOPRIVATE:+$GOPRIVATE,}github.com/stainless-sdks/warp-hr-go"

REPLACEMENT="${1:-"../warp-hr-go"}"
echo "==> Replacing Go SDK with $REPLACEMENT"
go mod edit -replace github.com/stainless-sdks/warp-hr-go="$REPLACEMENT"
go mod tidy -e
